from tkinter import *
top=Tk()
top.title("LISt OF ITEMS")
top.geometry("300x400")
l1=Label(top, text="List of cars", bg="purple")
l1.place(x=10,y=10)
lb=Listbox(top,height=10)
lb.insert(1,"Alto")
lb.insert(2,"Creta")
lb.insert(3,"Kia")
lb.insert(4,"Maruti 800")
lb.insert(5,"Mercedes")
lb.insert(6,"Audi")
lb.place(x=10,y=30)
l2=Label(top, text="List of Bikes", bg="Orange")
l2.place(x=160, y=10)
lb=Listbox(top,height=10)
lb.insert(1,"FZ")
lb.insert(2,"Splender")
lb.insert(3,"Unicorn")
lb.insert(4,"Bullet")
lb.insert(5,"Pulsar")
lb.insert(6,"Activa")
lb.place(x=160, y=30)
top.mainloop()


